onEvent('tags.items', event => {
    //Ores
    event.add('forge:ores', 'cavesandcliffs:deepslate_diamond_ore');
    event.add('forge:ores/diamond', 'cavesandcliffs:deepslate_diamond_ore');

    event.add('forge:ores', 'cavesandcliffs:deepslate_lapis_ore');
    event.add('forge:ores/lapis', 'cavesandcliffs:deepslate_lapis_ore');

    event.add('forge:ores', 'cavesandcliffs:deepslate_emerald_ore');
    event.add('forge:ores/emerald', 'cavesandcliffs:deepslate_emerald_ore');

    event.add('forge:ores', 'cavesandcliffs:deepslate_redstone_ore');
    event.add('forge:ores/redstone', 'cavesandcliffs:deepslate_redstone_ore');

    event.add('forge:ores', 'cavesandcliffs:deepslate_coal_ore');
    event.add('forge:ores/coal', 'cavesandcliffs:deepslate_coal_ore');

    event.remove('forge:cobblestone', 'minecraft:mossy_cobblestone');
    //Barrels
    event.add('forge:barrels/wooden', ['betternether:barrel_anchor_tree', 'betternether:barrel_nether_sakura', 'betternether:barrel_crimson', 'betternether:barrel_warped', 'betternether:barrel_stalagnate', 'betternether:barrel_reed', 'betternether:barrel_willow', 'betternether:barrel_wart', 'betternether:barrel_rubeus', 'betternether:barrel_mushroom', 'betternether:barrel_mushroom_fir', 'charm:oak_barrel', 'charm:spruce_barrel', 'charm:birch_barrel', 'charm:jungle_barrel', 'charm:acacia_barrel', 'charm:dark_oak_barrel', 'charm:crimson_barrel', 'charm:warped_barrel', 'crumbs:oak_barrel', 'crumbs:birch_barrel', 'crumbs:jungle_barrel', 'crumbs:acacia_barrel', 'crumbs:dark_oak_barrel', 'crumbs:crimson_barrel', 'crumbs:warped_barrel']);
    //Crafting Tables
    event.add('charm:crafting_tables', ['betternether:crafting_table_anchor_tree', 'betternether:crafting_table_nether_sakura', 'betternether:crafting_table_crimson', 'betternether:crafting_table_warped', 'betternether:crafting_table_stalagnate', 'betternether:crafting_table_reed', 'betternether:crafting_table_willow', 'betternether:crafting_table_wart', 'betternether:crafting_table_rubeus', 'betternether:crafting_table_mushroom', 'betternether:crafting_table_mushroom_fir', 'crumbs:spruce_crafting_table', 'crumbs:birch_crafting_table', 'crumbs:jungle_crafting_table', 'crumbs:acacia_crafting_table', 'crumbs:dark_oak_crafting_table', 'crumbs:crimson_crafting_table', 'crumbs:warped_crafting_table', 'cyclic:workbench', 'byg:aspen_crafting_table', 'byg:baobab_crafting_table', 'byg:blue_enchanted_crafting_table', 'byg:bulbis_crafting_table', 'byg:cherry_crafting_table', 'byg:cika_crafting_table', 'byg:cypress_crafting_table', 'byg:ebony_crafting_table', 'byg:ether_crafting_table', 'byg:fir_crafting_table', 'byg:green_enchanted_crafting_table', 'byg:holly_crafting_table', 'byg:imparius_crafting_table', 'byg:jacaranda_crafting_table', 'byg:lament_crafting_table', 'byg:mahogany_crafting_table', 'byg:mangrove_crafting_table', 'byg:maple_crafting_table', 'byg:nightshade_crafting_table', 'byg:palm_crafting_table', 'byg:pine_crafting_table', 'byg:rainbow_eucalyptus_crafting_table', 'byg:redwood_crafting_table', 'byg:skyris_crafting_table', 'byg:willow_crafting_table', 'byg:witch_hazel_crafting_table', 'byg:zelkova_crafting_table', 'byg:sythian_crafting_table', 'byg:embur_crafting_table', 'betterendforge:mossy_glowshroom_crafting_table', 'betterendforge:lacugrove_crafting_table', 'betterendforge:end_lotus_crafting_table', 'betterendforge:pythadendron_crafting_table', 'betterendforge:dragon_tree_crafting_table', 'betterendforge:tenanea_crafting_table', 'betterendforge:helix_tree_crafting_table', 'betterendforge:umbrella_tree_crafting_table', 'betterendforge:jellyshroom_crafting_table', 'betterendforge:lucernia_crafting_table']);

    event.add('refinedstorage:crafting_tables', ['betternether:crafting_table_anchor_tree', 'betternether:crafting_table_nether_sakura', 'betternether:crafting_table_crimson', 'betternether:crafting_table_warped', 'betternether:crafting_table_stalagnate', 'betternether:crafting_table_reed', 'betternether:crafting_table_willow', 'betternether:crafting_table_wart', 'betternether:crafting_table_rubeus', 'betternether:crafting_table_mushroom', 'betternether:crafting_table_mushroom_fir', 'crumbs:spruce_crafting_table', 'crumbs:birch_crafting_table', 'crumbs:jungle_crafting_table', 'crumbs:acacia_crafting_table', 'crumbs:dark_oak_crafting_table', 'crumbs:crimson_crafting_table', 'crumbs:warped_crafting_table', 'cyclic:workbench', 'byg:aspen_crafting_table', 'byg:baobab_crafting_table', 'byg:blue_enchanted_crafting_table', 'byg:bulbis_crafting_table', 'byg:cherry_crafting_table', 'byg:cika_crafting_table', 'byg:cypress_crafting_table', 'byg:ebony_crafting_table', 'byg:ether_crafting_table', 'byg:fir_crafting_table', 'byg:green_enchanted_crafting_table', 'byg:holly_crafting_table', 'byg:imparius_crafting_table', 'byg:jacaranda_crafting_table', 'byg:lament_crafting_table', 'byg:mahogany_crafting_table', 'byg:mangrove_crafting_table', 'byg:maple_crafting_table', 'byg:nightshade_crafting_table', 'byg:palm_crafting_table', 'byg:pine_crafting_table', 'byg:rainbow_eucalyptus_crafting_table', 'byg:redwood_crafting_table', 'byg:skyris_crafting_table', 'byg:willow_crafting_table', 'byg:witch_hazel_crafting_table', 'byg:zelkova_crafting_table', 'byg:sythian_crafting_table', 'byg:embur_crafting_table', 'betterendforge:mossy_glowshroom_crafting_table', 'betterendforge:lacugrove_crafting_table', 'betterendforge:end_lotus_crafting_table', 'betterendforge:pythadendron_crafting_table', 'betterendforge:dragon_tree_crafting_table', 'betterendforge:tenanea_crafting_table', 'betterendforge:helix_tree_crafting_table', 'betterendforge:umbrella_tree_crafting_table', 'betterendforge:jellyshroom_crafting_table', 'betterendforge:lucernia_crafting_table']);

    event.add('forge:workbenches', ['betternether:crafting_table_anchor_tree', 'betternether:crafting_table_nether_sakura', 'betternether:crafting_table_crimson', 'betternether:crafting_table_warped', 'betternether:crafting_table_stalagnate', 'betternether:crafting_table_reed', 'betternether:crafting_table_willow', 'betternether:crafting_table_wart', 'betternether:crafting_table_rubeus', 'betternether:crafting_table_mushroom', 'betternether:crafting_table_mushroom_fir', 'crumbs:spruce_crafting_table', 'crumbs:birch_crafting_table', 'crumbs:jungle_crafting_table', 'crumbs:acacia_crafting_table', 'crumbs:dark_oak_crafting_table', 'crumbs:crimson_crafting_table', 'crumbs:warped_crafting_table', 'cyclic:workbench', 'byg:aspen_crafting_table', 'byg:baobab_crafting_table', 'byg:blue_enchanted_crafting_table', 'byg:bulbis_crafting_table', 'byg:cherry_crafting_table', 'byg:cika_crafting_table', 'byg:cypress_crafting_table', 'byg:ebony_crafting_table', 'byg:ether_crafting_table', 'byg:fir_crafting_table', 'byg:green_enchanted_crafting_table', 'byg:holly_crafting_table', 'byg:imparius_crafting_table', 'byg:jacaranda_crafting_table', 'byg:lament_crafting_table', 'byg:mahogany_crafting_table', 'byg:mangrove_crafting_table', 'byg:maple_crafting_table', 'byg:nightshade_crafting_table', 'byg:palm_crafting_table', 'byg:pine_crafting_table', 'byg:rainbow_eucalyptus_crafting_table', 'byg:redwood_crafting_table', 'byg:skyris_crafting_table', 'byg:willow_crafting_table', 'byg:witch_hazel_crafting_table', 'byg:zelkova_crafting_table', 'byg:sythian_crafting_table', 'byg:embur_crafting_table', 'betterendforge:mossy_glowshroom_crafting_table', 'betterendforge:lacugrove_crafting_table', 'betterendforge:end_lotus_crafting_table', 'betterendforge:pythadendron_crafting_table', 'betterendforge:dragon_tree_crafting_table', 'betterendforge:tenanea_crafting_table', 'betterendforge:helix_tree_crafting_table', 'betterendforge:umbrella_tree_crafting_table', 'betterendforge:jellyshroom_crafting_table', 'betterendforge:lucernia_crafting_table']);
})